### ISSUE TITLE
Add the channels you want to index to channels.json?

### ISSUE THREAD

**Issue by TheRealUnknownDeveloper** [rogerfachini/YoutubeArchive#1]
Do we give the Channel ID, Username or URL?

**Comment by rogerfachini** [comment]
Channels are in the form of the full URL, which should be in one of these two forms (where data encased in <> is unique to that particular channel):

`https://www.youtube.com/user/<Channel-Name>`
`https://www.youtube.com/channel/<Channel-ID>`

NOTE: Do Not put a trailing slash or other information after the Channel ID or Channel name in the URL. Both of these two forms will NOT work:

`https://www.youtube.com/user/<Channel-Name>/`
`https://www.youtube.com/channel/<Channel-ID>/videos`

**Comment by TheRealUnknownDeveloper** [comment]
Fixed!
